version: "3.3"
services:
  corpvpn:
    image: tdharris/corpvpn
    build:
      context: ./
    container_name: corpvpn
    cap_add:
      - NET_ADMIN
    volumes:
      - /etc/localtime:/etc/localtime:ro
    env_file: .env
    ports:
      - ${VPN_PRIVOXY_PORT}:8118
      - ${VPN_SOCKS_PORT}:9118
      - ${DNS_PORT}:53/tcp
      - ${DNS_PORT}:53/udp
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.default.disable_ipv6=0
      - net.ipv6.conf.lo.disable_ipv6=0
      - net.ipv4.tcp_keepalive_intvl=1
      - net.ipv4.tcp_keepalive_probes=3
      - net.ipv4.tcp_keepalive_time=30
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
    healthcheck:
      test: /app/healthcheck.sh "${ENABLE_VPN}" "${ENABLE_DNS}" "${AUTO_RESTART_SERVICES}" || exit 1
      timeout: 30s
      interval: 5m
      start_period: 60s
      retries: 2
