version: "3.3"
services:
  corpvpn:
    image: tdharris/corpvpn:latest
    container_name: corpvpn
    restart: always
    cap_add:
      - NET_ADMIN
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DEFAULT_PUID=1000
      - DEFAULT_PGID=1000
      - ENABLE_VPN=false # Optional
      - ENABLE_DNS=true # Optional
      - AUTOHEAL_ENABLED=false # Optional
      - LAN_NETWORK=192.168.1.0/24 # Optional
      - VPN_SERVER= # Optional
      - VPN_USER= # Optional
      - VPN_PASS= # Optional
      - VPN_PROTOCOL=pulse # Optional
      - VPN_AUTH_GROUP="Smartphone Push" # Optional
    # env_file:
    #   - .env # Optional
    ports:
      - 8118:8118 # VPN_PRIVOXY_PORT
      - 9118:9118 # VPN_SOCKS_PORT
      - 5354:53/tcp # DNS_PORT
      - 5354:53/udp # DNS_PORT
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.default.disable_ipv6=0
      - net.ipv6.conf.lo.disable_ipv6=0
      - net.ipv4.tcp_keepalive_intvl=1
      - net.ipv4.tcp_keepalive_probes=3
      - net.ipv4.tcp_keepalive_time=30
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
    healthcheck:
      test: /app/healthcheck.sh || exit 1
      timeout: 30s
      interval: 60s
      start_period: 60s
      retries: 3
