name: Build and Push Docker Image

on:
  push:
    branches:
      - "main"
    paths:
      - "Dockerfile"
      - ".dockerignore"
      - "LICENSE.txt"
      - "root/**"
  workflow_dispatch:
    inputs:
      dryRun:
        description: "Skip pushing to Docker Hub"
        required: false
        default: false
        type: boolean

env:
  TEST_TAG: tdharris/corpvpn:test
  LATEST_TAG: tdharris/corpvpn:latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}

      - name: Test
        run: |
          docker run -e CI=true --rm ${{ env.TEST_TAG }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ${{ env.LATEST_TAG }}
          provenance: mode=max
          sbom: true
          push: ${{ !github.event.inputs.dryRun }}
